#enable_auto_fetch: true
collections_root: collections
archive_paths: archive
index_paths: indexes

#debug: true

use_js_obj_proxy: true
enable_memento: true
framed_replay: true

redirect_to_exact: true

# Uncomment to set banner colors and logo
# ui:
  # logo: path/relative/from/static/logo.png
  # logo_home_url: https://example.com
  # navbar_background_hex: 0c49b0
  # navbar_color_hex: fff
  # navbar_light_buttons: true
  # disable_printing: true

collections:
    all: $all
    live: $live
    ia:
        index:
            type: memento
            timegate_url: https://web.archive.org/web/{url}
            timemap_url: https://web.archive.org/web/timemap/link/{url}
            replay_url: https://web.archive.prg.org/web/{timestamp}/{url}

proxy:
    coll: all
    enable_banner: true
    enable_wombat: false
    enable_content_rewrite: false
