#!/usr/bin/env bash

FN="./connect_log.csv"
FN_BKP=${FN/.csv/_bkp.csv}


do_log() {
	local mask=$1
	local fn=$2
	find .. -name "$mask" -exec cat {} \; |
	{
		grep -a "CONNECT" | sed -r 's/[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+ - - //g' | sort | sed -r 's/\[(.+)\] "(.+)" (.+) (.+) (.+)/\1\t\2\t\3\t\4\t\5/g'
	} > $FN
}

if [ -f $FN_BKP ] ; then
	for f in `find .. -name "*.log.*"` ; do
		if [ "$f" -nt $FN_BKP ]; then
			rm $FN_BKP
			break
		fi
	done
fi

if [ ! $FN_BKP ] ; then
	do_log "*.log.*" $FN_BKP
fi
do_log "*.log" $FN

cat $FN_BKP $FN |
{
	grep "forum.kerbalspaceprogram.com" | cut -d $'\t' -f 1,5 | sed -r 's/(.+) (..:..):..\t(.+)/\1\t\2\t\3/g'
} > connect_log.time-per-connect.csv

cat connect_log.time-per-connect.csv |
{
	cut -d $'\t' -f 1,2 | uniq -c | awk '{ print($2"\t"$3"\t"$1); }'
} > connect_log.hits-per-minute.csv

