#!/usr/bin/env python
import sys
import redis

REDIS_URL = sys.argv[1]
KEY = REDIS_URL.split('/')[-1]

REDIS = redis.StrictRedis.from_url(REDIS_URL, decode_responses=True)

REDIS.delete(KEY)
for line in sys.stdin:
	line = line.rstrip()
	REDIS.zadd(KEY, 0, line)
