enable_auto_fetch: true
collections_root: collections
archive_paths: archive
index_paths: indexes

debug: true

use_js_obj_proxy: true
enable_memento: true
framed_replay: true

redirect_to_exact: true

# Uncomment to set banner colors and logo
# ui:
  # logo: path/relative/from/static/logo.png
  # logo_home_url: https://example.com
  # navbar_background_hex: 0c49b0
  # navbar_color_hex: fff
  # navbar_light_buttons: true
  # disable_printing: true

collections:
    all: $all
    live: $live

proxy:
    coll: forum-kerbalspaceprogram-com-media
    enable_banner: false
    enable_wombat: false
    enable_content_rewrite: false
    recording: true

recorder:
    source_coll: forum-kerbalspaceprogram-com-media
    rollover_size: 10000000000
    rollover_idle_secs: 3600
    filename_template: 'forum.kerbalspaceprogram.com-{timestamp}-media.warc'
    source_filter: live
    enable_put_custom_record: false
    cache: always
    dedup_policy: skip
    dedup_index_url: redis://macmini62:6379/0/pywb:forum.kerbalspaceprogram.com:cdxj
    autoindex: 30
